### ISSUE TITLE
background color changes depending on which part of the collapse-item is clicked

### ISSUE THREAD

**Issue by davidmaxwaterman** [Collaborne/paper-collapse-item#17]
Here's a codepen (thanks to @rubenstolk on the polymer slack channel) that demonstrates the issue :

http://codepen.io/davidmaxwaterman/pen/Omgmja

If you click on 'header' (or anywhere apart from the icon), the background turns grey.

If you click on the icon, then the background remains white. <-- expected behaviour for clicking anywhere

**Comment by davidmaxwaterman** [comment]
doh, I notice the same behaviour on the element's demos :

https://www.webcomponents.org/element/Collaborne/paper-collapse-item/demo/demo/index.html

**Comment by lauritowal** [comment]
@davidmaxwaterman  I think that is not a bug, but paper-item is behaving like this when focused. I also wanted to change this. 
It would be nice if there would be a mixin for to control paper-item. What do you think? @ankon, @ronnyroeller I would create a pull request.

**Comment by davidmaxwaterman** [comment]
While it is quite a while ago, I think what I reported is actually fixed now.

**Comment by lauritowal** [comment]
Apparently it is not fixed yet:
![notfixed](https://user-images.githubusercontent.com/3471924/33945736-26bc0754-e020-11e7-91be-f5af11e36408.png)

**Comment by davidmaxwaterman** [comment]
Well, as I said, it was a long time ago, but I think that image doesn't show this bug. This bug is about clicking on *the icon* and the background remaining white (while clicking anywhere else on the paper-collapse-item causes it to turn grey) ... that doesn't happen any more, ie clicking anywhere on the paper-collapse-item, including the icon, causes it to turn grey.
To me, the behaviour now looks consistent, even if it isn't what some may want. A mix-in might be good, yes.

**Comment by lauritowal** [comment]
@davidmaxwaterman alright. I've misunderstood you, sorry. What I wanted to do was to remove or change the grey overlay color when the element is focused. I've created a pull request for this: https://github.com/Collaborne/paper-collapse-item/pull/26
